### ISSUE TITLE
Astro logo in astrobrew pro navigation

### ISSUE THREAD

**Issue by TheOtterlord** [anthonylan/astrobrew#2]
Hi :wave:

When reviewing your Astro theme submission for the pro version of this theme, we noticed the full Astro logo in the navigation. If you could update this to replace the navigation logo, such as to the one in the free theme, and resubmit in the Astro theme portal, we'll take another look.

Let me know if you have any questions.

Thanks.

**Comment by anthonylan** [comment]
All done!
